export { extract } from './extract'
export { diff } from './diff'
export type { VisualDescriptor, VisualNode, VisualDifference, PseudoElement } from './types'
export type { DiffOptions } from './diff'
export { DEFAULT_PROPERTIES, TRACKED_ATTRIBUTES } from './schema'
