import type { FC } from 'hono/jsx'

interface DatePickerProps {
  id: string
  name: string
  label: string
  defaultValue?: string
  minDate?: string
  maxDate?: string
  required?: boolean
}

export const DatePicker: FC<DatePickerProps> = ({
  id,
  name,
  label,
  defaultValue,
  minDate,
  maxDate,
  required,
}) => (
  <flex-date-picker
    data-min-date={minDate}
    data-max-date={maxDate}
    data-default-value={defaultValue}
  >
    <label class="flex-label" for={id}>
      {label}
    </label>
    <div class="flex-date-picker__wrapper">
      <input
        class="flex-input flex-date-picker__external-input"
        id={id}
        name={name}
        type="text"
        placeholder="mm/dd/yyyy"
        value={defaultValue ? formatDateForDisplay(defaultValue) : ''}
        required={required}
      />
      <button
        type="button"
        class="flex-date-picker__button"
        aria-label="Toggle calendar"
      >
        <svg class="flex-icon" aria-hidden="true" focusable="false">
          <use href="/static/sprite.svg#event" />
        </svg>
      </button>
      <div
        class="flex-date-picker__calendar"
        hidden
        role="application"
        aria-label="Calendar"
      >
        <div class="flex-date-picker__calendar-header">
          <button
            type="button"
            class="flex-date-picker__nav flex-date-picker__nav--prev"
            aria-label="Previous month"
          >
            <svg class="flex-icon" aria-hidden="true" focusable="false">
              <use href="/static/sprite.svg#navigate_before" />
            </svg>
          </button>
          <button
            type="button"
            class="flex-date-picker__month-label"
            aria-label="Select month"
          />
          <button
            type="button"
            class="flex-date-picker__nav flex-date-picker__nav--next"
            aria-label="Next month"
          >
            <svg class="flex-icon" aria-hidden="true" focusable="false">
              <use href="/static/sprite.svg#navigate_next" />
            </svg>
          </button>
        </div>
        <table class="flex-date-picker__table" role="presentation">
          <thead>
            <tr>
              <th abbr="Sunday">Su</th>
              <th abbr="Monday">Mo</th>
              <th abbr="Tuesday">Tu</th>
              <th abbr="Wednesday">We</th>
              <th abbr="Thursday">Th</th>
              <th abbr="Friday">Fr</th>
              <th abbr="Saturday">Sa</th>
            </tr>
          </thead>
          <tbody>{/* Calendar days generated by client.ts */}</tbody>
        </table>
      </div>
    </div>
  </flex-date-picker>
)

/** Convert yyyy-mm-dd to mm/dd/yyyy for display */
function formatDateForDisplay(isoDate: string): string {
  const parts = isoDate.split('-')
  if (parts.length !== 3) return isoDate
  return `${parts[1]}/${parts[2]}/${parts[0]}`
}
