export const OPUS_MODEL_ID = 'us.anthropic.claude-opus-4-6-v1'
export const SONNET_MODEL_ID = 'us.anthropic.claude-sonnet-4-20250514-v1:0'
export const HAIKU_MODEL_ID = 'us.anthropic.claude-haiku-4-5-20251001-v1:0'
export const NOVA_PRO_MODEL_ID = 'us.amazon.nova-pro-v1:0'
export const NOVA_LITE_MODEL_ID = 'us.amazon.nova-lite-v1:0'
export const LLAMA_3_2_VISION_MODEL_ID = 'us.meta.llama3-2-90b-instruct-v1:0'
