github-webhook-secret: ENC[AES256_GCM,data:dQjHPR/HftiQYPikihjaTgsBCoWyu4CNjvGaPhB9wDza1YmBtOh5EKu//ezvBqFtvMoaVgZaDeaFGeDtyZ5VoQ==,iv:9QNDVlPg89c2PNbeTxAA8SaicMSMErUBW9YdIeSCxDY=,tag:pyOul+rFEB+nT4e7H0crTQ==,type:str]
github-token: ENC[AES256_GCM,data:v73DG8qBQL1xYq4JTLu+eABLpWf+NyU1y9WK5rhjOsgX7REhBcAhQw5f55Eq61s4B1mAiKwEv/+cGJE8L/JGkhzVUYLyKMALG9S4IKkkYBDta9jSVkDi4w5A5tlH,iv:D3gfsgjYcrzjrTtPX+HCtaRVFfAk5O9SKV1Z1GO0wEk=,tag:9tNQ3UmA10vLfoVgeFrgvw==,type:str]
github-client-id: ENC[AES256_GCM,data:2IkX2ABHwFfdBoMgdqCknEMZrhw=,iv:AH0O93Jgi9Ir9EQjpnpKJmVO9HKVMb3tR5T95LLDh/E=,tag:dQalbQw2S1VcKG9wj/fXDw==,type:str]
github-client-secret: ENC[AES256_GCM,data:j/D9CH0/pzwaZXbNTbwO8AyXJCKrPXUvOf+KtbDWKb/PM0ORhKmAaA==,iv:w66U3mwYvRqYGK2avJMZ33x4MtlAGziu1OttQSwsr48=,tag:XSRuOgn5u4PfUEHvLsyGkg==,type:str]
session-secret: ENC[AES256_GCM,data:fJ4AFqMpYK7CgdsOHsZVZRZcyIq1u/hyJB6RGLoxVhQw37VF7Hq5cYOJRL0=,iv:Rj4ToqRZJlL4j00jepcKn5VkyOnyGgKorVSFb6ZpUV4=,tag:gf+vg3VryYGFrwB/CEG7Mg==,type:str]
slack-webhook-url: ENC[AES256_GCM,data:YYQD9XMDqmgR0uUjesi/SM5lnTCC3mx75UyLbZAmttCxAIyD/jLIu4XlLz89A86Iib18hB/XJBvf8O8zgRH2qd9x1nsDm65p6zAHzcQrFQw3,iv:sOHL1+u3KIGCsGeX8qAagJWjf5FioXu1U2N1tm+Itdc=,tag:JQRCT8xMZkdEa/YofvcrCA==,type:str]
sops:
    age:
        - recipient: age1u7jjhjuhj9nuzdxygdjrv80z6xvea7pq73jezpqm2xl4s6ty2ajstyyfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL0lTY1paSm4xT3k0OW4r
            TW9oTENWU2Vsc3pjY2V6TEdsSFdpWkZZcHlVCk5zNm1EWFpwTDZrYzV3OG8rWHJ1
            c2N2VWNpa3RPRUxTQ05rQ0VlZ25tSmMKLS0tIGJxVEMvbjVLUENQTG9yQytDU1dR
            cVN6NzhIOGlJSmFiY0FqYkMxQkkxY3MK8xZqmh1DbJKiFraaW6kFF5jmYCsYNDNK
            JuuZ3TTqMpd/RjHMm+HlWsZtJEHu73BqYvC6jsudgrNjVn7QvBA7xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T19:45:01Z"
    mac: ENC[AES256_GCM,data:fArDqR+6nDhxckOtTxFx0XF4wBq03xF+VR3lvzA1AUk/CfNLKEU7ThJ0ST7TknfBNTR1EsH+PrFkwzLINvbluCr8enq1BWjdlU5o1cns3Bbfu3VHIzAH38AuDExnoUDLwwfD/biIhGsx+a4uj0pahLkpsPmECYAtx8O1542v+K8=,iv:MEcs1yjw4KlkvDTKNLLXOu6xU1SobagD+KEULQpG59w=,tag:NgAXDXQYlBUQRnbRV9LrwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
