github-webhook-secret: ENC[AES256_GCM,data:XGrQMWleGy5YlOP2a4pQWdu4g+swDtHq+GG4/s1eovbUigorp49hp34ysP7l5zEnvuLBz9vwUvxMjVRuJhW6jg==,iv:QJxWZ6KWOGAO684/gUKHi+LxPd1M2WoqtsdNs8/Kfuk=,tag:znpUJdnJOLaQU2CDA9T/Zw==,type:str]
sops:
    age:
        - recipient: age1u7jjhjuhj9nuzdxygdjrv80z6xvea7pq73jezpqm2xl4s6ty2ajstyyfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WjMxNDhQaUFTR2p3MmZ0
            aGcrK3VtL3pOR29zZU84U2VlaVFGWUFPOHd3CjRyUUM1MnlaczMyR1FkaUtIWDN6
            UzA2ZnJwUnFXK0VnV1pKRGJEUlR4V00KLS0tIDRmYXZPWWQ3dG5ac1V5UTNKTnN3
            OTZEZVYvSFlrbS9JTEhJam8rUi9sbXMKRtpBQvLDRXgiwQwjQj4SQZLlh6/cikIe
            tJylsePrwgBP3eVMTvhnVhGnmiOjI5HRgDHTfyQ7v2moNFty/4/ZAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T06:42:42Z"
    mac: ENC[AES256_GCM,data:nklUdUPuxG+d9n2ugPqSP8xhg4RZCwBMXn5QdXrZJQFNFWq5U5Eqyqy+Hz/OjGAByjkhl4KdGt1XcpCojGjUnVeB3MVkVfKZ4o7cEM+W9T/gknOCVyyexPvc3w4H1aaKI83p/lEs63Sd+IdCsfzjDyKOS632txXBI+TXKD7z7lE=,iv:Jv4aP+fnxFxNN84ouHIcp6M83nr9YGun/l2U7htNchg=,tag:8TxXXO+6ckl4XurkbUIfeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
