github-webhook-secret: ENC[AES256_GCM,data:XGrQMWleGy5YlOP2a4pQWdu4g+swDtHq+GG4/s1eovbUigorp49hp34ysP7l5zEnvuLBz9vwUvxMjVRuJhW6jg==,iv:QJxWZ6KWOGAO684/gUKHi+LxPd1M2WoqtsdNs8/Kfuk=,tag:znpUJdnJOLaQU2CDA9T/Zw==,type:str]
github-token: ENC[AES256_GCM,data:xmJDFNq0MKzUmThDbf4bgrxgpbuHAV9H/jO2/DUPpFmAu0uxBsKI73ku6pFeVApYZ2CRETipT1M1YNGqeUbilrnKmn8lUURYWAkagmjBrm2t36uj1oeTWm2plL9I,iv:TRy48MyO6Ey7uYsYcHdgDYn1ieYkdXgYa26sw7bK4us=,tag:jKU5K+5xUiytVnQE+x+tzA==,type:str]
github-client-id: ENC[AES256_GCM,data:h6ikeiasUbzY1ECY+3KUovz8z5Q=,iv:7gQ3OsbX8t6lb4Rr8OTfeg6CSmKRLilF0EOHaH+oD/g=,tag:1pqKXM9neQKXPvmTHQ1S4g==,type:str]
github-client-secret: ENC[AES256_GCM,data:MUFWmn1XVGR/yHdhLyjtVwop9KoXcjkRHVza7uUfE8WuB5knZdirLQ==,iv:1nUTXPTyguKvMx7QNJovsixQTTs7lCwdI+RPL432N90=,tag:byojEnpGNAMZ7duYuRLffQ==,type:str]
session-secret: ENC[AES256_GCM,data:4wSwuUM2fY+mrnSMbdGRVyoJfO04BwgDqEYT1zFQdjV1SYha1JWBn8KFbk4=,iv:nJiku31CJfkncf4UrMZUNN6JiJOaxQ3IsFJtfnOrtTU=,tag:5+er1u0/W1Wg7rVH0TSMbw==,type:str]
sops:
    age:
        - recipient: age1u7jjhjuhj9nuzdxygdjrv80z6xvea7pq73jezpqm2xl4s6ty2ajstyyfth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WjMxNDhQaUFTR2p3MmZ0
            aGcrK3VtL3pOR29zZU84U2VlaVFGWUFPOHd3CjRyUUM1MnlaczMyR1FkaUtIWDN6
            UzA2ZnJwUnFXK0VnV1pKRGJEUlR4V00KLS0tIDRmYXZPWWQ3dG5ac1V5UTNKTnN3
            OTZEZVYvSElrbS9JTEhJam8rUi9sbXMKRtpBQvLDRXgiwQwjQj4SQZLlh6/cikIe
            tJylsePrwgBP3eVMTvhnVhGnmiOjI5HRgDHTfyQ7v2moNFty/4/ZAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T15:50:55Z"
    mac: ENC[AES256_GCM,data:jwqa9aAYkqspbkqk6vy90LLSq5qni1fXKyA/1DSyYNchT0Pfik7987GO/k0ZZFrEnw3897Vp/zX32fNTuGGnWaKO1WMmiFryi50YXpqvz8pN5hW+ZmcBsYetJc3F7t7mqpNFPcgWlgtcf9ztTv6bzHUtoMIfFv4RknGYOBFRccM=,iv:CdG6T/ifl8K2I3C3/meMKK/bpnhf/FRb9//2xE2htBU=,tag:7pu5yraQMq/JvyZA1Jnnrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
